version: '3'

tasks:
 test:
   cmds:
   - clear
   - "dotnet test Localemgmt.Api.Test/Localemgmt.Api.Test.csproj"
   - "dotnet test Localemgmt.Application.Test/Localemgmt.Application.Test.csproj"
   - "dotnet test Localemgmt.Domain.Test/Localemgmt.Domain.Test.csproj"
   - "dotnet test EventSourcingStore.Test/EventSourcingStore.Test.csproj"
 run:
   cmds:
   - clear
   - "dotnet run --project Localemgmt.Api"
 reqa:
   cmds:
   - clear
   - ./Requests/LocaleItem/additem.sh
 requ:
   cmds:
   - clear
   - ./Requests/LocaleItem/updateItem.sh
 get:
   cmds:
   - clear
   - ./Requests/LocaleItem/getitems.sh
 context:
   cmds:
   - clear
   - ./Requests/LocaleItem/getcontext.sh
 aggr:
   cmds:
   - clear
   - ./Requests/LocaleItem/getaggregate.sh
 reqs:
   cmds:
   - clear
   - ./Requests/LocaleItem/additem.sh
   - ./Requests/LocaleItem/additem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
   - ./Requests/LocaleItem/updateItem.sh
