GET http://{{host}}:{{port}}/api/messages/test
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cuc29tZXRoaW5nLmNvbSIsImlhdCI6MTcyMjYxMjc2MywiZXhwIjoxNzU0MTQ4NzY0LCJhdWQiOiJ3d3cuc29tZXRoaW5nLmNvbSIsInN1YiI6Impyb2NrZXRAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoianJvY2tldCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Ik1hbmFnZXIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbCI6ImJlZUBleGFtcGxlLmNvbSJ9.LuVVp_2c5MHcBXr9OP9U7XAROlvCzu9j-v9tgt32gZo
